language: node_js
node_js: stable

before_script:
  - npm install -g gatsby-cli

cache:
  directories:
    - node_modules

before_deploy:
  - "npm run build"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: public
  on:
    branch: master

after_deploy:
  - echo zenojunior.com > CNAME